CREATE TABLE especialidades(
	idespecialidad INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
	creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE niveles(
	idnivel INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
	creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE usuarios(
	idusuario INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    idnivel INT UNSIGNED NOT NULL,
    cedula VARCHAR(200) UNIQUE NOT NULL,
	nombres VARCHAR(200) NOT NULL,
    apellidos VARCHAR(200) NOT NULL,
    correo VARCHAR(255) UNIQUE NOT NULL,
    cuenta VARCHAR(255) NOT NULL,
    clave VARCHAR(255) NOT NULL,
	creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (idnivel) REFERENCES niveles(idnivel)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE empresas(
	idempresa INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
	creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE medicos(
	idmedico INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    idespecialidad INT UNSIGNED NOT NULL,
    cedula VARCHAR(200) UNIQUE NOT NULL,
	nombres VARCHAR(200) NOT NULL,
    apellidos VARCHAR(200) NOT NULL,
	firma VARCHAR(200) NOT NULL,
	creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (idespecialidad) REFERENCES especialidades(idespecialidad)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE pacientes(
	idpaciente INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    idempresa INT UNSIGNED NOT NULL,
    cedula VARCHAR(200) UNIQUE NOT NULL,
	nombres VARCHAR(200) NOT NULL,
    apellidos VARCHAR(200) NOT NULL,
    sexo INT(1) NOT NULL, #1 Masculino , 2 Femenino
    correo VARCHAR(200) UNIQUE NOT NULL,
	creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (idempresa) REFERENCES empresas(idempresa)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE estudios(
	idestudio INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
	creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE estudiopaciente(
	idestudiopac INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    idpaciente INT UNSIGNED NOT NULL,
    idestudio INT UNSIGNED NOT NULL,
    idmedico INT UNSIGNED NOT NULL,
	fecha VARCHAR(200) NOT NULL,
    tecnica VARCHAR(200) NOT NULL,
    hallazgo VARCHAR(200) NOT NULL,
    conclusion VARCHAR(200) NOT NULL,
    imagen VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
	creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (idpaciente) REFERENCES pacientes(idpaciente)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

